version: '2.1'

volumes:
  db-data:
    name: db-data
  vendor:
    name: vendor
  var:
    name: var

services:
  mysql:
    image: mysql:8
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    command:
      - start-dev

  prestashop-git:
    hostname: ${PS_HOSTNAME:-localhost}
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - VERSION=${VERSION:-8.1-apache}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run_git.sh"]
    depends_on:
      - mysql
      - keycloak
    volumes:
      - ./:/var/www/html:delegated
