services:
  _defaults:
    public: true

  # COMMAND HANDLERS

  prestashop.core.domain.sql_management.command_handler.save_settings:
    class: 'PrestaShop\PrestaShop\Core\Domain\SqlManagement\CommandHandler\SaveSqlRequestSettingsHandler'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\SqlManagement\Command\SaveSqlRequestSettingsCommand'
        method: handle

  # QUERY HANDLERS

  prestashop.core.domain.sql_management.query_handler.get_sql_request_settings:
    class: 'PrestaShop\PrestaShop\Core\Domain\SqlManagement\QueryHandler\GetSqlRequestSettingsHandler'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\SqlManagement\Query\GetSqlRequestSettings'
        method: handle
