services:
  _defaults:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Alias\Validate\AliasValidator: ~

  PrestaShop\PrestaShop\Adapter\Alias\Repository\AliasRepository:
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\AddAliasHandler:
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Alias\Command\AddAliasCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Alias\QueryHandler\GetAliasForEditingHandler:
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Alias\Query\GetAliasForEditing
        method: handle

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\DeleteAliasHandler:
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Alias\Command\DeleteAliasCommand

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\BulkDeleteAliasHandler:
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Alias\Command\BulkDeleteAliasCommand

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\UpdateAliasStatusHandler:
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Alias\Command\UpdateAliasStatusCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\BulkUpdateAliasStatusHandler:
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Alias\Command\BulkUpdateAliasStatusCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\UpdateAliasHandler:
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Alias\Command\UpdateAliasCommand

  PrestaShop\PrestaShop\Adapter\Alias\QueryHandler\SearchForSearchTermHandler:
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Alias\Query\SearchForSearchTerm
