services:
  _defaults:
    public: true

  prestashop.adapter.attachment.command_handler.delete_attachment_handler:
    public: true
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\DeleteAttachmentHandler'
    parent: 'prestashop.adapter.attachment.command_handler.abstract_attachment_handler'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Command\DeleteAttachmentCommand', method: handle }

  prestashop.adapter.attachment.command_handler.bulk_delete_attachment_handler:
    public: true
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\BulkDeleteAttachmentsHandler'
    parent: 'prestashop.adapter.attachment.command_handler.abstract_attachment_handler'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Command\BulkDeleteAttachmentsCommand', method: handle }

  prestashop.adapter.attachment.query_handler.get_attachment_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\QueryHandler\GetAttachmentHandler'
    arguments:
      - !php/const _PS_DOWNLOAD_DIR_
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Query\GetAttachment', method: handle }

  prestashop.adapter.contact.query_handler.get_attachment_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\QueryHandler\GetAttachmentForEditingHandler'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Query\GetAttachmentForEditing', method: handle }

  prestashop.adapter.attachment.uploader.attachment_file_uploader:
    class: 'PrestaShop\PrestaShop\Adapter\File\Uploader\AttachmentFileUploader'
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.core.configuration.upload_size_configuration'

  prestashop.adapter.attachment.command_handler.abstract_attachment_handler:
    abstract: true
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\AbstractAttachmentHandler'
    arguments:
      - '@validator'

  prestashop.adapter.attachment.command_handler.edit_attachment_handler:
    public: true
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\EditAttachmentHandler'
    parent: 'prestashop.adapter.attachment.command_handler.abstract_attachment_handler'
    arguments:
      - '@prestashop.adapter.attachment.uploader.attachment_file_uploader'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Command\EditAttachmentCommand', method: handle }

  prestashop.adapter.attachment.command_handler.create_attachment_handler:
    public: true
    class: 'PrestaShop\PrestaShop\Adapter\Attachment\CommandHandler\AddAttachmentHandler'
    parent: 'prestashop.adapter.attachment.command_handler.abstract_attachment_handler'
    arguments:
      - '@prestashop.adapter.attachment.uploader.attachment_file_uploader'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Attachment\Command\AddAttachmentCommand', method: handle }

  PrestaShop\PrestaShop\Adapter\Attachment\AttachmentRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  prestashop.adapter.attachment.attachment_repository:
    alias: PrestaShop\PrestaShop\Adapter\Attachment\AttachmentRepository
    deprecated: ~

  prestashop.adapter.attachment.query_handler.get_attachment_information_handler:
    class: PrestaShop\PrestaShop\Adapter\Attachment\QueryHandler\GetAttachmentInformationHandler
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Attachment\AttachmentRepository'
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Attachment\Query\GetAttachmentInformation
        method: handle

  prestashop.adapter.attachment.query_handler.search_attachment_handler:
    class: PrestaShop\PrestaShop\Adapter\Attachment\QueryHandler\SearchAttachmentHandler
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Attachment\AttachmentRepository'
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Attachment\Query\SearchAttachment
        method: handle
