services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\AttributeGroup\AttributeGroupViewDataProvider:
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - '@PrestaShop\PrestaShop\Core\ConfigurationInterface'

  prestashop.adapter.product.attribute_group.attribute_group_view_data_provider:
    alias: PrestaShop\PrestaShop\Adapter\AttributeGroup\AttributeGroupViewDataProvider
    deprecated: ~

  PrestaShop\PrestaShop\Adapter\AttributeGroup\CommandHandler\DeleteAttributeGroupHandler:
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Command\DeleteAttributeGroupCommand'
        method: handle

  PrestaShop\PrestaShop\Adapter\AttributeGroup\CommandHandler\BulkDeleteAttributeGroupHandler:
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Command\BulkDeleteAttributeGroupCommand'
        method: handle

  PrestaShop\PrestaShop\Adapter\AttributeGroup\QueryHandler\GetAttributeGroupListHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Attribute\Repository\AttributeRepository'
      - '@PrestaShop\PrestaShop\Adapter\AttributeGroup\Repository\AttributeGroupRepository'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Query\GetAttributeGroupList'
        method: handle

  PrestaShop\PrestaShop\Adapter\Product\AttributeGroup\QueryHandler\GetProductAttributeGroupsHandler:
    autowire: true
    public: false
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Product\AttributeGroup\Query\GetProductAttributeGroups'
        method: handle

  PrestaShop\PrestaShop\Adapter\AttributeGroup\Repository\AttributeGroupRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
