services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\Attribute\CommandHandler\DeleteAttributeHandler:
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Attribute\Command\DeleteAttributeCommand'
        method: handle

  PrestaShop\PrestaShop\Adapter\Attribute\CommandHandler\BulkDeleteAttributeHandler:
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Attribute\Command\BulkDeleteAttributeCommand'
        method: handle

  PrestaShop\PrestaShop\Adapter\Attribute\Repository\AttributeRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
