services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\AddCartRuleHandler:
    autowire: true
    public: false
    tags:
      - { name: messenger.message_handler, handles: PrestaShop\PrestaShop\Core\Domain\CartRule\Command\AddCartRuleCommand, method: handle }

  PrestaShop\PrestaShop\Adapter\CartRule\QueryHandler\GetCartRuleForEditingHandler:
    autowire: true
    public: false
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\CartRule\Query\GetCartRuleForEditing'
        method: handle

  prestashop.adapter.cart_rule.query_handler.search_cart_rules_handler:
    class: PrestaShop\PrestaShop\Adapter\CartRule\QueryHandler\SearchCartRulesHandler
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
    tags:
      - { name: messenger.message_handler, handles: PrestaShop\PrestaShop\Core\Domain\CartRule\Query\SearchCartRules, method: handle }

  prestashop.adapter.cart_rule.command_handler.delete_cart_rule_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\DeleteCartRuleHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\CartRule\Command\DeleteCartRuleCommand'
        method: handle

  prestashop.adapter.cart_rule.command_handler.bulk_delete_cart_rule_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\BulkDeleteCartRuleHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\CartRule\Command\BulkDeleteCartRuleCommand'
        method: handle

  prestashop.adapter.cart_rule.command_handler.toggle_cart_rule_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\ToggleCartRuleStatusHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\CartRule\Command\ToggleCartRuleStatusCommand'
        method: handle

  prestashop.adapter.cart_rule.command_handler.bulk_toggle_cart_rule_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\BulkToggleCartRuleStatusHandler'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\CartRule\Command\BulkToggleCartRuleStatusCommand', method: handle }

  PrestaShop\PrestaShop\Adapter\CartRule\Validate\CartRuleValidator:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\CartRule\Repository\CartRuleRepository:
    autowire: true
    public: false
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\EditCartRuleHandler:
    autowire: true
    public: false
    tags:
      - { name: messenger.message_handler, handles: PrestaShop\PrestaShop\Core\Domain\CartRule\Command\EditCartRuleCommand, method: handle }

  PrestaShop\PrestaShop\Adapter\CartRule\CartRuleActionFiller:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\CartRule\CommandHandler\SetCartRuleRestrictionsHandler:
    autowire: true
    public: false
    tags:
      - { name: tactician.handler, command: PrestaShop\PrestaShop\Core\Domain\CartRule\Command\SetCartRuleRestrictionsCommand }
