services:
  _defaults:
    public: true
    bind:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\AddFeatureHandler:
    autowire: true
    public: false
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Feature\Command\AddFeatureCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\EditFeatureHandler:
    autowire: true
    public: false
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Feature\Command\EditFeatureCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Feature\QueryHandler\GetFeatureForEditingHandler:
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Feature\Query\GetFeatureForEditing
        method: handle

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\AddFeatureValueHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureRepository'
      - '@PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureValueRepository'
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Feature\Command\AddFeatureValueCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\EditFeatureValueHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureValueRepository'
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Feature\Command\EditFeatureValueCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Feature\QueryHandler\GetFeatureValueForEditingHandler:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureValueRepository'
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Feature\Query\GetFeatureValueForEditing
        method: handle

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\DeleteFeatureHandler:
    autowire: true
    public: false
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Feature\Command\DeleteFeatureCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\BulkDeleteFeatureHandler:
    autowire: true
    public: false
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Feature\Command\BulkDeleteFeatureCommand
        method: handle

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\DeleteFeatureValueHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\DeleteFeatureValueCommand

  PrestaShop\PrestaShop\Adapter\Feature\CommandHandler\BulkDeleteFeatureValueHandler:
    autowire: true
    public: false
    tags:
      - name: tactician.handler
        command: PrestaShop\PrestaShop\Core\Domain\Feature\Command\BulkDeleteFeatureValueCommand

  PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureRepository:
    autowire: true
    public: false

  PrestaShop\PrestaShop\Adapter\Feature\Validate\FeatureValidator: ~

  PrestaShop\PrestaShop\Adapter\Feature\Validate\FeatureValueValidator: ~

  PrestaShop\PrestaShop\Adapter\Feature\Repository\FeatureValueRepository:
    autowire: true
    public: true
