services:
  _defaults:
    public: true

  # Command handlers

  prestashop.adapter.manufacturer.manufacturer_logo_thumbnail_provider:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerLogoThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'

  prestashop.adapter.manufacturer.command_handler.toggle_manufacturer_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\ToggleManufacturerStatusHandler'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Manufacturer\Command\ToggleManufacturerStatusCommand', method: handle }

  prestashop.adapter.manufacturer.command_handler.bulk_toggle_manufacturer_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\BulkToggleManufacturerStatusHandler'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Manufacturer\Command\BulkToggleManufacturerStatusCommand', method: handle }

  prestashop.adapter.manufacturer.command_handler.delete_manufacturer_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\DeleteManufacturerHandler'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Manufacturer\Command\DeleteManufacturerCommand', method: handle }

  prestashop.adapter.manufacturer.command_handler.delete_manufacturer_logo_image_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\DeleteManufacturerLogoImageHandler'
    arguments:
      - !php/const _PS_MANU_IMG_DIR_
      - !php/const _PS_TMP_IMG_DIR_
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\Manufacturer\Command\DeleteManufacturerLogoImageCommand'
        method: handle

  prestashop.adapter.manufacturer.command_handler.bulk_delete_manufacturer_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\BulkDeleteManufacturerHandler'
    tags:
      - { name: 'messenger.message_handler', handles: 'PrestaShop\PrestaShop\Core\Domain\Manufacturer\Command\BulkDeleteManufacturerCommand', method: handle }

  prestashop.adapter.manufacturer.query_handler.get_manufacturer_for_editing:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\QueryHandler\GetManufacturerForEditingHandler'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\Manufacturer\Query\GetManufacturerForEditing'
        method: handle

  prestashop.adapter.manufacturer.command_handler.edit_manufacturer_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\EditManufacturerHandler'
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\Manufacturer\Command\EditManufacturerCommand'
        method: handle

  prestashop.adapter.manufacturer.command_handler.add_manufacturer_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\CommandHandler\AddManufacturerHandler'
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\Manufacturer\Command\AddManufacturerCommand'
        method: handle

  prestashop.adapter.manufacturer.query_handler.get_manufacturer_for_viewing_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\QueryHandler\GetManufacturerForViewingHandler'
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\Manufacturer\Query\GetManufacturerForViewing
        method: handle

  PrestaShop\PrestaShop\Adapter\Manufacturer\Repository\ManufacturerRepository: ~
