services:
  _defaults:
    public: true

  prestashop.adapter.order_message.command_handler.add_order_message_handler:
    class: PrestaShop\PrestaShop\Adapter\OrderMessage\CommandHandler\AddOrderMessageHandler
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\OrderMessage\Command\AddOrderMessageCommand
        method: handle

  prestashop.adapter.order_message.command_handler.edit_order_message_handler:
    class: PrestaShop\PrestaShop\Adapter\OrderMessage\CommandHandler\EditOrderMessageHandler
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\OrderMessage\Command\EditOrderMessageCommand
        method: handle

  prestashop.adapter.order_message.query_handler.get_order_message_for_editing_handler:
    class: PrestaShop\PrestaShop\Adapter\OrderMessage\QueryHandler\GetOrderMessageForEditingHandler
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\OrderMessage\Query\GetOrderMessageForEditing
        method: handle

  prestashop.adapter.order_message.command_handler.delete_order_message_handler:
    class: PrestaShop\PrestaShop\Adapter\OrderMessage\CommandHandler\DeleteOrderMessageHandler
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\OrderMessage\Command\DeleteOrderMessageCommand
        method: handle

  prestashop.adapter.order_message.command_handler.bulk_delete_order_message_handler:
    class: PrestaShop\PrestaShop\Adapter\OrderMessage\CommandHandler\BulkDeleteOrderMessageHandler
    tags:
      - name: messenger.message_handler
        handles: PrestaShop\PrestaShop\Core\Domain\OrderMessage\Command\BulkDeleteOrderMessageCommand
        method: handle

  prestashop.adapter.order_message.order_message_provider:
    class: 'PrestaShop\PrestaShop\Adapter\OrderMessage\OrderMessageProvider'
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
