services:
  _defaults:
    public: true

  prestashop.adapter.order_state.command_handler.add_order_state:
    class: 'PrestaShop\PrestaShop\Adapter\OrderState\CommandHandler\AddOrderStateHandler'
    autoconfigure: true

  prestashop.adapter.order_state.query_handler.get_order_state_for_editing:
    class: 'PrestaShop\PrestaShop\Adapter\OrderState\QueryHandler\GetOrderStateForEditingHandler'
    autoconfigure: true

  prestashop.adapter.order_state.command_handler.edit_order_state_handler:
    class: 'PrestaShop\PrestaShop\Adapter\OrderState\CommandHandler\EditOrderStateHandler'
    autoconfigure: true

  prestashop.adapter.order_state.command_handler.delete_order_state_handler:
    class: 'PrestaShop\PrestaShop\Adapter\OrderState\CommandHandler\DeleteOrderStateHandler'
    autoconfigure: true

  prestashop.adapter.order_state.command_handler.bulk_delete_order_state_handler:
    class: 'PrestaShop\PrestaShop\Adapter\OrderState\CommandHandler\BulkDeleteOrderStateHandler'
    autoconfigure: true
