services:
  _defaults:
    public: true

  prestashop.adapter.state.command_handler.create_state_handler:
    class: 'PrestaShop\PrestaShop\Adapter\State\CommandHandler\AddStateHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\State\Command\AddStateCommand'
        method: handle

  prestashop.adapter.state.command_handler.edit_state_handler:
    class: 'PrestaShop\PrestaShop\Adapter\State\CommandHandler\EditStateHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\State\Command\EditStateCommand'
        method: handle

  prestashop.adapter.state.command_handler.toggle_state_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\State\CommandHandler\ToggleStateStatusHandler'
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\State\Command\ToggleStateStatusCommand'
        method: handle

  prestashop.adapter.state.query_handler.get_state_for_editing_handler:
    class: 'PrestaShop\PrestaShop\Adapter\State\QueryHandler\GetStateForEditingHandler'
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\State\Query\GetStateForEditing'
        method: handle

  prestashop.adapter.state.command_handler.delete_state_handler:
    class: 'PrestaShop\PrestaShop\Adapter\State\CommandHandler\DeleteStateHandler'
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\State\Command\DeleteStateCommand'
        method: handle

  prestashop.adapter.state.command_handler.bulk_delete_state_handler:
    class: 'PrestaShop\PrestaShop\Adapter\State\CommandHandler\BulkDeleteStateHandler'
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\State\Command\BulkDeleteStateCommand'
        method: handle

  prestashop.adapter.state.command_handler.bulk_toggle_state_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\State\CommandHandler\BulkToggleStateStatusHandler'
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\State\Command\BulkToggleStateStatusCommand'
        method: handle
