services:
  _defaults:
    public: true

  prestashop.adapter.supplier.provider.supplier_logo:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\SupplierLogoThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'
      - '@PrestaShop\PrestaShop\Adapter\ImageManager'

  prestashop.adapter.supplier.provider.supplier_address:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\SupplierAddressProvider'

  prestashop.adapter.supplier.supplier_order_validator:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\SupplierOrderValidator'

  # Command handlers

  prestashop.adapter.supplier.command_handler.abstract_delete_supplier_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\AbstractDeleteSupplierHandler'
    abstract: true
    arguments:
      - '@prestashop.adapter.supplier.supplier_order_validator'
      - '@prestashop.adapter.supplier.provider.supplier_address'
      - '@PrestaShop\PrestaShop\Adapter\Product\Update\ProductSupplierUpdater'
      - '%database_prefix%'
    public: false

  prestashop.adapter.supplier.command_handler.toggle_supplier_status_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\ToggleSupplierStatusHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Command\ToggleSupplierStatusCommand'
        method: handle

  prestashop.adapter.supplier.command_handler.delete_supplier_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\DeleteSupplierHandler'
    parent: 'prestashop.adapter.supplier.command_handler.abstract_delete_supplier_handler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Command\DeleteSupplierCommand'
        method: handle
    public: true

  prestashop.adapter.supplier.command_handler.delete_supplier_logo_image_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\DeleteSupplierLogoImageHandler'
    arguments:
      - !php/const _PS_SUPP_IMG_DIR_
      - !php/const _PS_TMP_IMG_DIR_
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Command\DeleteSupplierLogoImageCommand'
        method: handle

  prestashop.adapter.supplier.command_handler.bulk_delete_supplier_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\BulkDeleteSupplierHandler'
    parent: 'prestashop.adapter.supplier.command_handler.abstract_delete_supplier_handler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Command\BulkDeleteSupplierCommand'
        method: handle
    public: true

  prestashop.adapter.supplier.command_handler.bulk_disable_supplier_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\BulkDisableSupplierHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Command\BulkDisableSupplierCommand'
        method: handle

  prestashop.adapter.supplier.command_handler.bulk_enable_supplier_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\BulkEnableSupplierHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Command\BulkEnableSupplierCommand'
        method: handle

  prestashop.adapter.supplier.query_handler.get_supplier_for_viewing_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\QueryHandler\GetSupplierForViewingHandler'
    arguments:
      - '@prestashop.core.localization.locale.context_locale'
      - '@=service("prestashop.adapter.legacy.configuration").get("PS_CURRENCY_DEFAULT")'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Query\GetSupplierForViewing'
        method: handle

  prestashop.adapter.supplier.command_handler.add_supplier_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\AddSupplierHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Command\AddSupplierCommand'
        method: handle

  prestashop.adapter.supplier.query_handler.get_supplier_for_editing:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\QueryHandler\GetSupplierForEditingHandler'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Query\GetSupplierForEditing'
        method: handle

  prestashop.adapter.supplier.command_handler.edit_supplier_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Supplier\CommandHandler\EditSupplierHandler'
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Supplier\Command\EditSupplierCommand'
        method: handle

  PrestaShop\PrestaShop\Adapter\Supplier\Repository\SupplierRepository: ~
