services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\Title\CommandHandler\AddTitleHandler:
    autowire: true
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Title\Command\AddTitleCommand'
        method: handle

  PrestaShop\PrestaShop\Adapter\Title\CommandHandler\EditTitleHandler:
    autowire: true
    tags:
      - name: 'messenger.message_handler'
        handles: 'PrestaShop\PrestaShop\Core\Domain\Title\Command\EditTitleCommand'
        method: handle

  prestashop.adapter.title.title_image_thumbnail_provider:
    class: 'PrestaShop\PrestaShop\Adapter\Title\TitleImageThumbnailProvider'
    arguments:
      - '@prestashop.core.image.parser.image_tag_source_parser'
      - '@PrestaShop\PrestaShop\Adapter\ImageManager'
      - !php/const _PS_GENDERS_DIR_

  prestashop.adapter.title.command_handler.delete_title_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Title\CommandHandler\DeleteTitleHandler'
    autowire: true
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\Title\Command\DeleteTitleCommand'
        method: handle

  prestashop.adapter.title.command_handler.bulk_delete_title_handler:
    class: 'PrestaShop\PrestaShop\Adapter\Title\CommandHandler\BulkDeleteTitleHandler'
    autowire: true
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\Title\Command\BulkDeleteTitleCommand'
        method: handle

  PrestaShop\PrestaShop\Adapter\Title\QueryHandler\GetTitleForEditingHandler:
    autowire: true
    tags:
      - name: messenger.message_handler
        handles: 'PrestaShop\PrestaShop\Core\Domain\Title\Query\GetTitleForEditing'
        method: handle

  PrestaShop\PrestaShop\Adapter\Title\Repository\TitleRepository:
    autowire: true

  PrestaShop\PrestaShop\Adapter\Title\Validate\TitleValidator: ~
