name: Check the label 'Need autoupgrade PR'

on: pull_request_target

jobs:
  install_prestashop_and_dump_base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker build
        run: docker compose build prestashop-git

      - name: Build dependency
        run: docker compose run --rm prestashop-git composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Create base database
        run: docker compose run --rm mysql mysql -hmysql -uroot -pprestashop -e "CREATE DATABASE presta_base;"

      - name: Install shop
        run: docker compose run --rm prestashop-git php install-dev/index_cli.php \
          --step=database --db_server=mysql:3306 --db_name=presta_base --db_user=root --db_password=prestashop --prefix=ps_ --db_clear=1 \
          --domain=localhost:8001 --firstname="Marc" --lastname="Beier" \
          --password=Toto123! --email=demo@prestashop.com --language=fr --country=fr \
          --newsletter=0 --send_email=0 --ssl=0

      - name: Export dump
        run: docker compose run --rm mysql sh -c "exec mysqldump -hmysql -uroot --no-data --compact -pprestashop presta_base" > dump_base.sql

      - name: Upload dump
        uses: actions/upload-artifact@v4
        with:
          name: dump_base
          path: |
            dump_base.sql

  install_prestashop_and_dump_head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Docker build
        run: docker compose build prestashop-git

      - name: Build dependency
        run: docker compose run --rm prestashop-git composer install --no-interaction

      - name: Create head database
        run: docker compose run --rm mysql mysql -hmysql -uroot -pprestashop -e "CREATE DATABASE presta_head;"

      - name: Install shop
        run: docker compose run --rm prestashop-git php install-dev/index_cli.php \
          --step=database --db_server=mysql:3306 --db_name=presta_head --db_user=root --db_password=prestashop --prefix=ps_ --db_clear=1 \
          --domain=localhost:8001 --firstname="Marc" --lastname="Beier" \
          --password=Toto123! --email=demo@prestashop.com --language=fr --country=fr \
          --newsletter=0 --send_email=0 --ssl=0

      - name: Export dump
        run: docker compose run --rm mysql sh -c "exec mysqldump -hmysql -uroot --no-data --compact -pprestashop presta_head" > dump_head.sql

      - name: Upload dump
        uses: actions/upload-artifact@v4
        with:
          name: dump_head
          path: |
            dump_head.sql

  verify_diff:
    needs: [install_prestashop_and_dump_base, install_prestashop_and_dump_head]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - name: Create diff
        run: git diff ./dump_head/dump_head.sql ./dump_base/dump_base.sql > sql-diff.txt | true

      - name: Upload diff
        uses: actions/upload-artifact@v4
        with:
          name: sql_diff
          path: |
            sql-diff.txt

  add_label:
    name: Verify Need autoupgrade PR
    needs: [verify_diff]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - run: |
          if [ -s sql_diff/sql-diff.txt ]; then
            gh pr edit "$NUMBER" --add-label "$LABELS"
          else
            gh pr edit "$NUMBER" --remove-label "$LABELS"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
          LABELS: Needs autoupgrade PR
